fix(test): TradeControllerTest -  TradeControllerTest.testCreateTradeValidationFailure_MissingBook:175 Status expected:<400> but was:<201> - Problem: The API was returning a status code 201 instead of 400. A book name was not provided so we expect it to fail with a bad request response. - Root Cause: There was no form of validation for bookName in the TradeController class.Although there is some form of validation in the validateReferenceData(Trade trade) in the TradeService class but it looks like the controller did not properly catch that. - Solution: I added @NotNull annotation to the bookName field in TradeDTO and also added null checks for bookName and counterpartyName in the TradeController.java class. - Impact: This ensure proper book name validation  and rejects any trade creation requests missing both Book and Counterparty.